---
- name: Stack Port Down Automation
  hosts: localhost
  gather_facts: no

  vars:
    snow_instance: 
    url: "https://{{ snow_instance }}/api/now/table/incident ?sysparm_query=assignment_group={{ assignment_group_sys_id }}"
    short_description: "Stack Port Down Alert"
    assignment_group: "NOC"

  vars_files:
  - secrets.yml
   
    

  tasks:

    - name: Create ServiceNow Incident
      url: "https://{{ snow_instance }}/api/now/table/incident?sysparm_query=assignment_group={{ assignment_group_sys_id }}"
      include_role:
        name: create_incident

    - name: Check switch port status
      include_role:
        name: checkport

    - name: Close incident if port is UP
      include_role:
        name: update_incident
      when: port_status == "up"

    - name: Transfer incident to NOC if port still DOWN
      include_role:
        name: notify_noc
      when: port_status == "down"
