---
- name: Validate inputs
  ansible.builtin.assert:
    that:
      - snow_user is defined
      - snow_pass is defined
      - snow_api_base is defined

- name: Set timestamp
  ansible.builtin.set_fact:
    now_iso: "{{ lookup('pipe','date -Is') }}"

- name: Fetch staging records
  include_tasks: snow_fetch.yml

- name: Process device checks
  include_tasks: device_check.yml
  when: staging_records | length > 0

- name: Update ServiceNow
  include_tasks: snow_update.yml
